CREATE TABLE ConnectionMetaData ( Z_PK INTEGER PRIMARY KEY, hasChanged INTEGER, device INTEGER, changedTime TIMESTAMP, connectionDate TIMESTAMP );
CREATE TABLE DailyAirQualityData ( Z_PK INTEGER PRIMARY KEY, airQualityEnumRawValue INTEGER, airQualityIndex INTEGER, hasChanged INTEGER, changedTime TIMESTAMP, date TIMESTAMP );
CREATE TABLE DailyUserFeelingData ( Z_PK INTEGER PRIMARY KEY, hasChanged INTEGER, time INTEGER, userFeeling INTEGER, changedTime TIMESTAMP, date TIMESTAMP );
CREATE TABLE DeviceData ( Z_PK INTEGER PRIMARY KEY, doseCount INTEGER, hasChanged INTEGER, inhalerNameType INTEGER, isActive INTEGER, lastRecordId INTEGER, remainingDoseCount INTEGER, medication INTEGER, changedTime TIMESTAMP, expirationDate TIMESTAMP, lastConnection TIMESTAMP, dateCode VARCHAR, hardwareRevision VARCHAR, lotCode VARCHAR, manufacturerName VARCHAR, nickname VARCHAR, serialNumber VARCHAR, sharedKey VARCHAR, softwareRevision VARCHAR );
CREATE TABLE InhaleEventData ( Z_PK INTEGER PRIMARY KEY, closeTime INTEGER, doseId INTEGER, duration INTEGER, eventTime INTEGER, eventUID INTEGER, hasChanged INTEGER, inhaleEventTime INTEGER, inhalePeak INTEGER, inhaleTimeToPeak INTEGER, isValidInhale INTEGER, status INTEGER, time INTEGER, timeZoneOffset INTEGER, upperThresholdDuration INTEGER, upperThresholdTime INTEGER, device INTEGER, changedTime TIMESTAMP, date INTEGER, cartridgeUID VARCHAR );
CREATE TABLE MedicationData ( Z_PK INTEGER PRIMARY KEY, hasChanged INTEGER, initialDoseCount INTEGER, medicationClassification INTEGER, minimumDoseInterval INTEGER, minimumScheduleInterval INTEGER, numberOfMonthsBeforeExpiration INTEGER, overdoseInhalationCount INTEGER, changedTime TIMESTAMP, brandName VARCHAR, drugUID VARCHAR, genericName VARCHAR );
CREATE TABLE PrescriptionData ( Z_PK INTEGER PRIMARY KEY, dosesPerDay INTEGER, hasChanged INTEGER, inhalesPerDose INTEGER, medication INTEGER, changedTime TIMESTAMP, prescriptionDate TIMESTAMP );
CREATE TABLE NotificationSettingData ( Z_PK INTEGER PRIMARY KEY, changedTime TIMESTAMP, hasChanged INTEGER, enabled INTEGER, name VARCHAR, repeatType INTEGER, repeatTypeData INTEGER );
CREATE TABLE Z_METADATA (version VARCHAR, databaseName VARCHAR, dateModified TIMESTAMP);
CREATE INDEX ZCONNECTIONMETADATA_ZDEVICE_INDEX ON ConnectionMetaData (device);
CREATE UNIQUE INDEX ZCONNECTIONMETADATA_ZCONNECTIONDATE_INDEX ON ConnectionMetaData (connectionDate, device);
CREATE UNIQUE INDEX ZDAILYAIRQUALITYDATA_ZDATE_INDEX ON DailyAirQualityData (date);
CREATE UNIQUE INDEX ZDAILYUSERFEELINGDATA_ZDATE_INDEX ON DailyUserFeelingData (date);
CREATE INDEX ZDEVICEDATA_ZMEDICATION_INDEX ON DeviceData (medication);
CREATE UNIQUE INDEX ZDEVICEDATA_ZSERIALNUMBER_INDEX ON DeviceData (serialNumber);
CREATE INDEX ZDEVICEDATA_ZISACTIVE_INDEX ON DeviceData (isActive, lastConnection);
CREATE INDEX ZINHALEEVENTDATA_ZDATE_INDEX ON InhaleEventData (date, time, timeZoneOffset);
CREATE INDEX ZINHALEEVENTDATA_ZDEVICE_INDEX ON InhaleEventData (device);
CREATE INDEX ZPRESCRIPTIONDATA_ZMEDICATION_INDEX ON PrescriptionData (medication);
CREATE INDEX ZMEDICATIONDATA_ZMEDICATIONCLASSIFICATION_INDEX ON MedicationData (medicationClassification);
INSERT INTO Z_METADATA (version, databaseName) VALUES (1, 'EncryptedRespiratoryApp.sqlite');
UPDATE Z_METADATA set dateModified = (select strftime('%s', 'now')) where databaseName = 'EncryptedRespiratoryApp.sqlite';
